@apiurl = http://localhost:8080/api/products

# POST - create new product
POST {{apiurl}}
Content-Type: application/json

{
    "name": "SSD 500GB NVME",
    "price": 400,
    "condition": "new",
    "quantityPurchased": 2,
    "soldAmount": 4,
    "quantityInStock": 6
}
###

# GET - return all products

GET {{apiurl}}
Content-Type: application/json

