@apiurl = http://localhost:8080/api/products

# POST - create new product
POST {{apiurl}}
Content-Type: application/json

{
    "name": "SSD 480GB NVME",
    "price": 400,
    "condition": "new"
}
###

# GET - return all products

GET {{apiurl}}
Content-Type: application/json

